name: todo_bloc
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.4
  hive_generator: ^2.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl: ^0.18.1
  flutter_native_splash: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# After add flutter native splash we need to write manually steps below :
flutter_native_splash :
  #light color
  color: "#f7f6f1"
  # dark color
  dark_color: "#272727"
  # Add image
  image: assets/images/note_app.jpg
  dark_image: assets/images/note_app.jpg
  android_12:
    image: assets/images/note_app.jpg
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/note_app.jpg
    icon_background_color_dark: "#272727"



  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

